name: validate

on:
  push:
    branches:
      - "**"

env:
  DOCKER_IMAGE: localhost:5000/name/app

jobs:
  validate:
    name: validate docker build
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: ${{ env.DOCKER_IMAGE }}
          tag-sha: true
          tag-semver: |
            v{{version}}
            v{{major}}.{{minor}}
            v{{major}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./app
          file: ./app/Dockerfile
          platforms: linux/amd64
          push: false
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Check digest
        run: |
          if [ -z "${{ steps.docker_build.outputs.digest }}" ]; then
            echo "::error::Digest should not be empty"
            exit 1
          fi